### ISSUE TITLE
How to add a ServletContextListener implementation to InMemoryRestServer

### ISSUE THREAD

**Issue by JathinSanghvi** [mp911de/rest-api-test#1]
i liked your InMemory Rest Server. And i am using it to test my REST service.
Can you suggest a method to execute contextInitialized() method of ServletContextListener Impl class.
So that i can set some properties during server start

**Comment by mp911de** [comment]
Create a PR, so we can discuss the code.

**Comment by JathinSanghvi** [comment]
Added a pull request.

**Comment by JathinSanghvi** [comment]
any thoughts how to solve it ?

**Comment by mp911de** [comment]
I added some comments to PR #2

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
