### ISSUE TITLE
need help novice user of rest-api from this repo

### ISSUE THREAD

**Issue by balu2903** [mp911de/rest-api-test#3]
Hi , 

I am a novice user or rest-api automation implementation, i have successfully imported this as maven project into my eclipse and no errors. run appTest.java as junit test. it is resulted as passed, but not able to see the junit test report and execution time is 0.0 milliseconds. please guide me . my email is balu.api.testing@gmail.com.

**Comment by mp911de** [comment]
Should be fixed with #4
